[package]
name = "msg-store"
version = "0.1.0"
authors = ["joshua"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "benches"
harness = false

